ALTER TABLE sap_customer_master
ADD COLUMN Customer_MOB1 VARCHAR(20) AFTER customer_name,
ADD COLUMN customer_MOB2 VARCHAR(20) AFTER Customer_MOB1,
ADD COLUMN ACTIVE_IND CHAR(1) DEFAULT 'A' AFTER customer_MOB2,
ADD COLUMN EMAIL_ADDRESS VARCHAR(255) AFTER ACTIVE_IND,
ADD COLUMN Address TEXT AFTER EMAIL_ADDRESS,
ADD COLUMN PIN VARCHAR(10) AFTER Address;
