ALTER TABLE contractor_annexure3a 
ADD COLUMN epf_code VARCHAR(50) AFTER unskilled_count,
ADD COLUMN is_epf_registered TINYINT(1) DEFAULT 0 AFTER epf_code,
ADD COLUMN esi_code VARCHAR(50) AFTER is_epf_registered,
ADD COLUMN is_esi_registered TINYINT(1) DEFAULT 0 AFTER esi_code,
ADD COLUMN wage_declaration TEXT AFTER is_esi_registered,
ADD COLUMN salary_category VARCHAR(100) AFTER wage_declaration,
ADD COLUMN insurance_policy_name VARCHAR(255) AFTER salary_category,
ADD COLUMN insurance_policy_no VARCHAR(100) AFTER insurance_policy_name,
ADD COLUMN insurance_validity DATE AFTER insurance_policy_no,
ADD COLUMN insurance_workers_count INT AFTER insurance_validity,
ADD COLUMN labour_license_no VARCHAR(100) AFTER insurance_workers_count,
ADD COLUMN labour_license_issue_date DATE AFTER labour_license_no,
ADD COLUMN labour_license_expiry_date DATE AFTER labour_license_issue_date,
ADD COLUMN labour_license_issued_by VARCHAR(255) AFTER labour_license_expiry_date,
ADD COLUMN pin_code VARCHAR(20) AFTER labour_license_issued_by,
ADD COLUMN created_by INT NULL AFTER pin_code,
ADD COLUMN updated_by INT NULL AFTER created_by,
ADD COLUMN updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
